### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Pardeeprawat001** [creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4#16]
Hi Creative Team,

Can you please help me out to get rid of the below issue?

I just want to know that can we put whole vue structure/files on live server? I am curious and clueless as well . 

Here i am explaining what i have done so far.
1) On local run the build and upload it on live server and everything is working fine all the connectivity and all.

Question:
My question is can we run the vue project on server without build? I want all the files are kept on server just like local so if i change anything it will directly effect on my site. now i have to do changes on local then have to run build command and then upload ity on server.

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products! 

Unfortunately you cannot do that, you need the build to compile files. 

Let us know if we can help with anything else.

Best
