### ISSUE TITLE
Problem with Json API backend

### ISSUE THREAD

**Issue by waldoalvarez00** [creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4#17]
Hello:

The backend laravel Json API is trying to authenticate with Oauth table instead of the users table (and crashing with null access since is empty). Is there any configuration I need to change to make it use the users table instead? There is a user + password sample in the login page but is not working for me. I am also looking to remove the oauth part from the backend. I am not sure if I would be reinventing the wheel if I rewrite that code and is is somewhere else. IMHO should authenticate against users table by default.

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products! 

Our Laravel API Project product is using Laravel Passport for authentication, which provides a full OAuth2 server implementation. This is the reason you should follow the installation steps:
- Generate application key: php artisan key:generate
- Install Laravel Passport: php artisan passport:install

Let us know if we can help with anything else.
