### ISSUE TITLE
[Bug] Upgrade assistance

### ISSUE THREAD

**Issue by Delamaine** [creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4#20]
### Version
1.5.2
### Reproduction link
https://github.com/creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4/issues/19
### Operating System
Windows 10 / WSL
### Device
PC
### Browser & Version
Chrome 112.0.5615.138
### Steps to reproduce
I purchased this solution and downloaded the fullstack archive (laravel backend and vue frontend) then downloaded the 1.5.2 archive. I overwrite all similarly named files in the fullstack archive with the files from the 1.5.2 archive and then proceeded to build.

The build completes successfully (some warnings) and then launched dev server (npm run dev) which takes me to the dashboard page instead of the login page (which I expected). I would like to understand how to apply the upgrade on 'pro' archive to version 1.5.2 please as it seems like some files in 1.5.2 is overwriting functionality in pro (taking it back to a demo of the solution essentially)

I reviewed all documentation but did not see (detailed) instructions on how to apply upgrade.

Any assistance / guidance appreciated.

Thanks
### What is expected?
'npm run dev' should launch frontend at login page and allow login. 
### What is actually happening?
after upgrade it launches to dashboard and no login / logout option available

---
### Additional comments
I run laravel backend on nginx.

**Comment by Delamaine** [comment]
You release updates (downloaded via VUEJS button in attachment) to keep the solution (downloaded via (LARAVEL button in attachment) aligned to node package changes, in this case you released version 1.5.2 which I am trying to apply.

What are the steps to apply the 'update' to the 'solution' as I am experiencing issues as described before.

![image](https://github.com/creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4/assets/3479514/213982d1-cedb-4d58-a052-c6d054f483ab)

Thanks

PS i was copying the files in archive to the right to the left hand archive in next attachment - 
![image](https://github.com/creativetimofficial/ct-vue-material-dashboard-laravel-pro-bs4/assets/3479514/d8e11ec8-355f-4075-96f5-2a72ee5f7730)

**Comment by teamupdivision** [comment]
Hello @Delamaine,
The folder you are trying to paste is a completely different product and it will not work by just copy/paste unfortunately.

We are soon releasing Vue Material PRO Laravel based on the latet Material Theme https://www.creative-tim.com/product/vue-material-dashboard-2-pro, but again you will not be able to copy/paste it on the old product to make work.

Best

**Comment by Delamaine** [comment]
The file i downloaded was provided by clicking on the same product so you have an incorrect link, could you please rectify.

Seeing as the initial product release was years ao and there has been no updates it is quite time-consuming to get it to compile. Please provide steps to get it to compile, expected node version etc.

**Comment by teamupdivision** [comment]
Hello, sorry for the delayed reply.
YOu should consider Laravel 9.x and Node.js v16.x LTS
Best
